### ISSUE TITLE
Strange number to character conversion in 'display'

### ISSUE THREAD

**Issue by lukq** [tgrysztar/fasmg#12]
```
display 209,210,211,10
display 21'
```
The two lines above, when compiled, print three different characters on the first line of output, and one character on the second line. The character on the second line seems to be the same as character with code 210.
Is that interpretation of number 21' by design, or possibly a bug?
version: g.jmhx

Also, in the Fasm g manual there is missing a complete description of integer literals syntax, i.e. no mention that ' characters are accepted.

**Comment by bitRAKE** [comment]
Numbers allow both ' and _ to increase readability - this is by design.
