### ISSUE TITLE
Invalid PE32/64 image directory bug

### ISSUE THREAD

**Issue by Vityacv** [tgrysztar/fasmg#4]
lea rax,[test1] ;no fixups generated
mov rax,test1 ;fixups generated

When used lea, in data directory fasm set invalid pointer IMAGE_DIRECTORY_ENTRY_BASERELOC
Also this bug present in fasm1

Test on ms link vs2017 with options:
`link.exe /release /subsystem:windows /nocoffgrpinfo /dll /dynamicbase /entry:Main "test64.obj"`

It worked correctly: IMAGE_DIRECTORY_ENTRY_BASERELOC/size are 0 and module is relocatable.
If build "exe" windows will load it with ASLR, then there is no message like "This app can't run on your PC"

**Comment by Vityacv** [comment]
Possible solution for fasm1 when 

align 4
data fixups
end data

are used.


In FORMATS.INC:

...
jb process_directories

push edx

cmpdword [edx+5*8],0
jnefinish_pe_relocations
...

pop edx
cmp dword[edx+5*8+4],0 ;check if size still 0
jnz pe_relocations_fix
mov dword[edx+5*8],0 ;fix invalid pointer
pe_relocations_fix:

mov ebx,[code_start]
sub ebx,[stub_size]
mov ecx,edi
sub ecx,ebx
mov ebp,ecx
shr ecx,1
xor eax,eax
cdq
calculate_checksum:
...

**Comment by tgrysztar** [comment]
The main function of this particular macro package is to emulate fasm 1, even if it reproduces some of fasm's problems.

For a discussion of this specific behavior of fasm 1, please see [one of the relevant threads](https://board.flatassembler.net/topic.php?t=20300) on fasm's message board.

By the way, I suggest posting bug reports on fasm's forums, as it's been done traditionally for nearly 20 years. I may not always be up to date with reports done on the other channels, the message board is usually the quickest to reach me.
